package com.kaukajarvisoft.tas.policy;

public enum Role {
	CREATE_QUESTION_LIST, EDIT_QUESTION_LIST, DELETE_QUESTION_LIST,CREATE_QUESTION, EDIT_QUESTION, ADD_QUESTION_TO_LIST, 
	REMOVE_QUESTION_FROM_LIST, CREATE_TEST, EDIT_TEST, VIEW_QUESTION, VIEW_TEST, VIEW_QUESTION_LIST

}
